const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORAGE="notes-master-v1";
const seedFolders=[{id:"personal",name:"Personal"},{id:"work",name:"Work"},{id:"study",name:"Study"}];
const state={view:"all",search:"",sort:"updated",selected:null,theme:localStorage.getItem("notes-theme")||"light",folders:JSON.parse(localStorage.getItem(STORAGE+"-folders")||"null")||seedFolders,notes:JSON.parse(localStorage.getItem(STORAGE+"-notes")||"[]")};

function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function save(){localStorage.setItem(STORAGE+"-notes",JSON.stringify(state.notes));localStorage.setItem(STORAGE+"-folders",JSON.stringify(state.folders))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function plain(html){let d=document.createElement("div");d.innerHTML=html;return (d.textContent||d.innerText||"").replace(/\s+/g," ").trim()}
function words(html){return plain(html).split(/\s+/).filter(Boolean).length}
function fmtDate(v){if(!v)return"—";const d=new Date(v),diff=Math.floor((Date.now()-d)/60000);if(diff<1)return"now";if(diff<60)return diff+"m";if(diff<1440)return Math.floor(diff/60)+"h";if(diff<10080)return Math.floor(diff/1440)+"d";return d.toLocaleDateString(undefined,{month:"short",day:"numeric"})}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}
function setTheme(t){state.theme=t;document.body.classList.toggle("dark",t==="dark");localStorage.setItem("notes-theme",t);$("#themeBtn").textContent=t==="dark"?"☀":"☾"}setTheme(state.theme)

function folderName(id){return state.folders.find(f=>f.id===id)?.name||"No folder"}
function counts(){let a=state.notes;$("#allCount").textContent=a.filter(n=>!n.trashed).length;$("#pinnedCount").textContent=a.filter(n=>n.pinned&&!n.trashed&&!n.archived).length;$("#favoriteCount").textContent=a.filter(n=>n.favorite&&!n.trashed).length;$("#archiveCount").textContent=a.filter(n=>n.archived&&!n.trashed).length;$("#trashCount").textContent=a.filter(n=>n.trashed).length}
function renderFolders(){let counts={};state.notes.forEach(n=>{if(n.folderId&&!n.trashed)counts[n.folderId]=(counts[n.folderId]||0)+1});$("#folderList").innerHTML=state.folders.map(f=>`<button class="folder-item ${state.view==="folder:"+f.id?"active":""}" data-folder="${f.id}">📁 ${esc(f.name)} <b>${counts[f.id]||0}</b></button>`).join("")||'<span class="muted" style="padding:10px">No folders</span>';$$(".folder-item").forEach(b=>b.onclick=()=>{state.view="folder:"+b.dataset.folder;state.selected=null;update()})}
function viewTitle(){const m={all:"All Notes",pinned:"Pinned",favorites:"Favorites",archive:"Archive",trash:"Trash"};if(m[state.view])return m[state.view];if(state.view.startsWith("folder:"))return folderName(state.view.slice(7));return"Notes"}
function visibleNotes(){let a=state.notes.filter(n=>{if(state.view==="trash")return n.trashed;if(state.view==="archive")return n.archived&&!n.trashed;if(state.view==="pinned")return n.pinned&&!n.archived&&!n.trashed;if(state.view==="favorites")return n.favorite&&!n.trashed&&!n.archived;if(state.view==="all")return !n.trashed&&!n.archived;return state.view.startsWith("folder:")?n.folderId===state.view.slice(7)&&!n.trashed&&!n.archived:false});if(state.search){const q=state.search.toLowerCase();a=a.filter(n=>(n.title+" "+plain(n.body)+" "+(n.tags||[]).join(" ")).toLowerCase().includes(q))}return a.sort((a,b)=>{if(state.sort==="title")return a.title.localeCompare(b.title);if(state.sort==="created")return new Date(b.createdAt)-new Date(a.createdAt);if(state.sort==="favorites")return Number(b.favorite)-Number(a.favorite)||new Date(b.updatedAt)-new Date(a.updatedAt);if(state.sort==="pinned")return Number(b.pinned)-Number(a.pinned)||new Date(b.updatedAt)-new Date(a.updatedAt);return new Date(b.updatedAt)-new Date(a.updatedAt)})}
function renderList(){let list=visibleNotes(),wrap=$("#notesList");$("#resultsCount").textContent=list.length+" note"+(list.length===1?"":"s");wrap.innerHTML=list.map(n=>`<article class="note-card ${state.selected===n.id?"active":""}" data-id="${n.id}"><div class="row"><div class="note-title">${esc(n.title||"Untitled note")}</div><div class="card-icons">${n.pinned?"📌":""}${n.favorite?"★":""}</div></div><div class="note-excerpt">${esc(plain(n.body)||"Empty note")}</div><div class="note-tags">${(n.tags||[]).slice(0,3).map(t=>`<span class="tag">#${esc(t)}</span>`).join("")}</div><div class="row" style="margin-top:9px"><span class="note-date">${fmtDate(n.updatedAt)}</span><span class="note-date">${esc(folderName(n.folderId))}</span></div></article>`).join("");wrap.querySelectorAll(".note-card").forEach(c=>c.onclick=()=>selectNote(c.dataset.id));const empty=list.length===0;$("#emptyList").classList.toggle("hidden",!empty);if(empty){let titles={trash:"Trash is empty",archive:"No archived notes",pinned:"No pinned notes",favorites:"No favorite notes"};$("#emptyTitle").textContent=titles[state.view]||"No notes found";$("#emptyText").textContent=state.search?"Try a different search.":"Create a note to get started.";$("#emptyAction").style.display=state.view==="trash"||state.view==="archive"||state.view==="pinned"||state.view==="favorites"?"none":""}}
function renderEditor(){const n=state.notes.find(n=>n.id===state.selected);if(!n){$("#editor").classList.add("hidden");$("#editorEmpty").classList.remove("hidden");$("#editorPane").classList.remove("open");return}$("#editorEmpty").classList.add("hidden");$("#editor").classList.remove("hidden");$("#editorPane").classList.add("open");$("#noteTitle").value=n.title||"";$("#noteBody").innerHTML=n.body||"";$("#noteFolderMeta").textContent=folderName(n.folderId);$("#noteUpdatedMeta").textContent="Updated "+fmtDate(n.updatedAt);$("#noteCreatedMeta").textContent="Created "+new Date(n.createdAt).toLocaleString();$("#wordCount").textContent=words(n.body)+" words";$("#pinBtn").textContent=n.pinned?"📌":"📌";$("#favoriteBtn").style.color=n.favorite?"#f59e0b":"";$("#archiveBtn").textContent=n.archived?"▰":"▱";$("#deleteBtn").title=n.trashed?"Delete forever":"Move to trash"}
function update(){counts();renderFolders();$("#viewTitle").textContent=viewTitle();$("#searchInput").value=state.search;renderList();renderEditor()}
function createNote(){const now=new Date().toISOString(),n={id:uid(),title:"",body:"",tags:[],folderId:state.view.startsWith("folder:")?state.view.slice(7):null,pinned:false,favorite:false,archived:false,trashed:false,createdAt:now,updatedAt:now};state.notes.unshift(n);state.selected=n.id;state.view="all";save();update();setTimeout(()=>$("#noteTitle").focus(),50)}
function selectNote(id){state.selected=id;renderList();renderEditor();if(innerWidth<=760)$("#editorPane").classList.add("open")}
function updateNote(patch){let n=state.notes.find(n=>n.id===state.selected);if(!n)return;Object.assign(n,patch,{updatedAt:new Date().toISOString()});save();update()}
function getCurrent(){return state.notes.find(n=>n.id===state.selected)}
function noteText(){const n=getCurrent();return n?plain(n.body):""}

$("#newNoteBtn").onclick=createNote;$("#emptyAction").onclick=createNote;$("#themeBtn").onclick=()=>setTheme(state.theme==="dark"?"light":"dark");
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");$("#backToListBtn").onclick=()=>$("#editorPane").classList.remove("open");
$("#searchInput").oninput=e=>{state.search=e.target.value;renderList()}
$("#sortSelect").onchange=e=>{state.sort=e.target.value;renderList()}
$$(".nav-item").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.selected=null;$("#sidebar").classList.remove("open");update()});
$("#noteTitle").oninput=e=>{const e2=encodeURIComponent(e.target.value);let n=getCurrent();if(!n)return;n.title=e.target.value;n.updatedAt=new Date().toISOString();$("#saveState").textContent="Saving…";$("#saveState").classList.add("saving");save();renderList();clearTimeout(window.saveTimer);window.saveTimer=setTimeout(()=>{$("#saveState").textContent="Saved";$("#saveState").classList.remove("saving");},350)}
$("#noteBody").oninput=()=>{let n=getCurrent();if(!n)return;n.body=$("#noteBody").innerHTML;n.updatedAt=new Date().toISOString();$("#saveState").textContent="Saving…";$("#saveState").classList.add("saving");$("#wordCount").textContent=words(n.body)+" words";save();renderList();clearTimeout(window.saveTimer);window.saveTimer=setTimeout(()=>{$("#saveState").textContent="Saved";$("#saveState").classList.remove("saving");},350)}
$("#pinBtn").onclick=()=>{let n=getCurrent();if(n)updateNote({pinned:!n.pinned})}
$("#favoriteBtn").onclick=()=>{let n=getCurrent();if(n)updateNote({favorite:!n.favorite})}
$("#archiveBtn").onclick=()=>{let n=getCurrent();if(n)updateNote({archived:!n.archived,trashed:false})}
$("#deleteBtn").onclick=()=>{let n=getCurrent();if(!n)return;if(n.trashed){if(confirm("Delete this note permanently?")){state.notes=state.notes.filter(x=>x.id!==n.id);state.selected=null;save();update()}}else{updateNote({trashed:true,archived:false});state.selected=null;update()}}
$("#moreBtn").onclick=()=>{$("#moreModal").classList.remove("hidden")}
$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.add("hidden"));
$$("[data-cmd]").forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);$("#noteBody").focus();$("#noteBody").dispatchEvent(new Event("input"))});
$("#insertChecklistBtn").onclick=()=>{document.execCommand("insertUnorderedList");document.execCommand("insertText",false,"☐ ");$("#noteBody").focus();$("#noteBody").dispatchEvent(new Event("input"))}
$("#insertCodeBtn").onclick=()=>{document.execCommand("formatBlock",false,"pre");$("#noteBody").focus();$("#noteBody").dispatchEvent(new Event("input"))}
$("#insertLinkBtn").onclick=()=>{const u=prompt("Enter URL");if(u)document.execCommand("createLink",false,u);$("#noteBody").focus();$("#noteBody").dispatchEvent(new Event("input"))}
$("#clearFormatBtn").onclick=()=>{document.execCommand("removeFormat");$("#noteBody").focus();$("#noteBody").dispatchEvent(new Event("input"))}
$("#duplicateBtn").onclick=()=>{const n=getCurrent();if(!n)return;const now=new Date().toISOString(),copy={...n,id:uid(),title:(n.title||"Untitled note")+" (Copy)",createdAt:now,updatedAt:now,trashed:false};state.notes.unshift(copy);state.selected=copy.id;$("#moreModal").classList.add("hidden");save();update();toast("Note duplicated")}
$("#moveBtn").onclick=()=>{const s=$("#moveFolderSelect");s.innerHTML='<option value="">No folder</option>'+state.folders.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join("");const n=getCurrent();if(n)s.value=n.folderId||"";$("#moreModal").classList.add("hidden");$("#moveModal").classList.remove("hidden")}
$("#saveMoveBtn").onclick=()=>{const n=getCurrent();if(n)updateNote({folderId:$("#moveFolderSelect").value||null});$("#moveModal").classList.add("hidden")}
$("#printBtn").onclick=()=>{const n=getCurrent();if(!n)return;const w=window.open("","_blank");w.document.write(`<html><head><title>${esc(n.title||"Untitled note")}</title><style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:20px;line-height:1.7}h1{line-height:1.2}</style></head><body><h1>${esc(n.title||"Untitled note")}</h1>${n.body}</body></html>`);w.document.close();w.print();$("#moreModal").classList.add("hidden")}
$("#copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText((getCurrent()?.title||"Untitled note")+"\n\n"+noteText());toast("Copied note text")}catch{toast("Clipboard access unavailable")}$("#moreModal").classList.add("hidden")}
$("#focusBtn").onclick=()=>document.body.classList.toggle("focus-mode");
$("#addFolderBtn").onclick=()=>{$("#folderNameInput").value="";$("#folderModal").classList.remove("hidden");setTimeout(()=>$("#folderNameInput").focus(),30)}
$("#saveFolderBtn").onclick=()=>{const name=$("#folderNameInput").value.trim();if(!name)return toast("Enter a folder name");if(state.folders.some(f=>f.name.toLowerCase()===name.toLowerCase()))return toast("Folder already exists");state.folders.push({id:uid(),name});save();$("#folderModal").classList.add("hidden");update()}
$("#exportBtn").onclick=()=>{const payload={app:"Notes Master",version:1,exportedAt:new Date().toISOString(),folders:state.folders,notes:state.notes};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="notes-master-backup.json";a.click();URL.revokeObjectURL(a.href);toast("Backup exported")}
$("#importBtn").onclick=()=>$("#importInput").click();
$("#importInput").onchange=e=>{const file=e.target.files[0];if(!file)return;const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);if(!Array.isArray(p.notes))throw Error();state.notes=p.notes;state.folders=Array.isArray(p.folders)?p.folders:state.folders;state.selected=null;save();update();toast("Backup imported")}catch{toast("Invalid notes backup")}};rd.readAsText(file);e.target.value=""}
document.addEventListener("keydown",e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="n"){e.preventDefault();createNote()}if(e.key==="/"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();$("#searchInput").focus()}if(e.key==="Escape"){$$(".modal").forEach(m=>m.classList.add("hidden"));$("#sidebar").classList.remove("open");$("#editorPane").classList.remove("open")}});
window.addEventListener("beforeunload",save);
update();
